### ISSUE TITLE
Older branches

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/mozilla.oidc.accessproxy#37]
@gdestuynder What are your thoughts on what we should do with these two branches with content in them that's not made it into `master`?

* [This patch](https://github.com/mozilla-iam/mozilla.oidc.accessproxy/compare/gdestuynder-patch-1)
* [API Proxying](https://github.com/mozilla-iam/mozilla.oidc.accessproxy/compare/spa)

**Comment by gdestuynder** [comment]
:spa is still in use
the other one is just my generic patch this in branch, can be delete. i dont think its worth an issue though :)
